name: Ruff
on: [push, pull_request]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: chartboost/ruff-action@v1
        with:
          src: "./app"
          version: 0.12.10
          args: "format --check"
      - uses: chartboost/ruff-action@v1
        with:
          src: "./app"
          version: 0.12.10
          args: "check --extend-select I"
